"use client";

import { useMemo, useState } from "react";
import type { BattlefieldApiResponse } from "@/lib/intelligence/types/battlefield";

interface IntelligenceDashboardShellProps { initialData: BattlefieldApiResponse; }

export default function IntelligenceDashboardShell({ initialData }: IntelligenceDashboardShellProps) {
  const [data] = useState(initialData);
  const items = useMemo(() => [...data.items].sort((a, b) => a.symbol.localeCompare(b.symbol)), [data.items]);
  return <main style={{ padding: 24, color: "#e2e8f0", background: "#020617", minHeight: "100vh" }}><div style={{ maxWidth: 1200, margin: "0 auto" }}><h1>Battlefield Intelligence & Capital Deployment Console</h1><p style={{ color: "#94a3b8" }}>Generated: {new Date(data.generatedAt).toLocaleString()}</p>{items.map((it) => <section key={it.symbol} style={{ marginTop: 16, border: "1px solid #1e293b", borderRadius: 12, padding: 14 }}><h2>{it.symbol} • Primary Opportunity: {it.primaryOpportunity}</h2><p>{it.battlefieldSummary}</p><h3>1) Swing Battlefield</h3><p>{it.swing.bias} | Confidence {it.swing.confidence}% | Entry {it.swing.entryZone} | Stop {it.swing.stopZone} | Targets {it.swing.target1}/{it.swing.target2}</p><h3>2) Long-Term Battlefield</h3><p>{it.longTerm.bias} | Confidence {it.longTerm.confidence}% | Accumulation {it.longTerm.accumulationZone} | 1Y {it.longTerm.expected1Y}</p><h3>3) Whale / Trap Intelligence</h3><p>Trap {it.whale.trapRisk}, Exhaustion {it.whale.exhaustionRisk}, Flow {it.whale.unusualFlow}. {it.whale.interpretation}</p><h3>4) Macro Terrain</h3><p>{it.macro.terrain} | Volatility {it.macro.volatilityState} | Sector pressure {it.macro.sectorPressure}</p><h3>5) Political / World Risk</h3><p>Political {it.politics.politicalRisk}, Regulatory {it.politics.regulatoryRisk}, Geopolitical {it.politics.geopoliticalPressure}</p><h3>6) Sentiment Confirmation</h3><p>{it.sentiment.sentimentState} ({it.sentiment.confirmationStrength}) — {it.sentiment.interpretation}</p><h3>7) Capital Deployment Plan</h3><p>{it.deployment.bestDeployment} via {it.deployment.preferredInstrument} | Sizing: {it.deployment.sizingAggressiveness}</p><h3>8) Entry / Exit Map</h3><p>Entry: {it.deployment.entryRange} • Stop: {it.deployment.stopRange} • Target: {it.deployment.targetRange} • Return: {it.deployment.estimatedReturn} • R/R: {it.deployment.riskReward}</p>{it.warnings.length ? <ul>{it.warnings.map((w) => <li key={w}>{w}</li>)}</ul> : null}</section>)}</div></main>;
}
