import type { CapitalDeploymentOutput, LongEngineOutput, MacroModuleOutput, SentimentModuleOutput, SwingEngineOutput, WhaleModuleOutput } from "@/lib/intelligence/types/battlefield";

export function buildCapitalDeployment(swing: SwingEngineOutput, longTerm: LongEngineOutput, whale: WhaleModuleOutput, macro: MacroModuleOutput, sentiment: SentimentModuleOutput): CapitalDeploymentOutput {
  if (whale.trapRisk === "High") return { bestDeployment: "Wait for Pullback", preferredInstrument: "None", entryRange: swing.entryZone, stopRange: swing.stopZone, targetRange: `${swing.target1} / ${swing.target2}`, expectedMove: "Unclear until trap risk cools", estimatedReturn: "2% to 6%", riskReward: swing.riskReward, sizingAggressiveness: "Starter Only", deploymentReason: "Trap risk elevated; require confirmation before full deployment." };
  if (longTerm.speculativeRiskScore >= 72) return { bestDeployment: "Starter Position", preferredInstrument: "Shares", entryRange: swing.entryZone, stopRange: swing.stopZone, targetRange: `${swing.target1} / ${swing.target2}`, expectedMove: "3% to 8%", estimatedReturn: "6% to 14%", riskReward: "1:1.8", sizingAggressiveness: "Starter Only", deploymentReason: "Speculative-risk cap active: tactical exposure only with tight deployment controls." };
  if (swing.bias === "Swing Put Opportunity" && macro.terrain === "Risk-Off") return { bestDeployment: "Buy Puts", preferredInstrument: "Puts", entryRange: swing.entryZone, stopRange: swing.stopZone, targetRange: `${swing.target1} / ${swing.target2}`, expectedMove: "-4% to -9%", estimatedReturn: "12% to 30%", riskReward: "1:2.2", sizingAggressiveness: "Half Size", deploymentReason: "Rejection plus weak terrain supports tactical downside exposure." };
  if (longTerm.bias === "Long Buy" || longTerm.bias === "Shares Preferred") return { bestDeployment: "Buy Shares", preferredInstrument: "Shares", entryRange: longTerm.accumulationZone, stopRange: swing.stopZone, targetRange: `${longTerm.expected6M} / ${longTerm.expected1Y}`, expectedMove: longTerm.expected6M, estimatedReturn: longTerm.expected1Y, riskReward: "1:2+", sizingAggressiveness: macro.terrain === "Risk-Off" || longTerm.speculativeRiskScore >= 55 ? "Half Size" : "Full Size", deploymentReason: "Fundamental lane leads; deploy gradually with macro-aware sizing and speculative-risk controls." };
  return { bestDeployment: sentiment.sentimentState === "Hype Risk" ? "Watch Only" : "Starter Position", preferredInstrument: "Shares", entryRange: swing.entryZone, stopRange: swing.stopZone, targetRange: `${swing.target1} / ${swing.target2}`, expectedMove: "3% to 8%", estimatedReturn: "5% to 12%", riskReward: swing.riskReward, sizingAggressiveness: "Starter Only", deploymentReason: "Mixed battlefield signals; preserve optionality." };
}
